import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  createExportDataset,
  createExportFilename,
  ExportError,
  normalizeTableReference,
} from "../src/export/export-dataset.mjs";
import { exportInsertSql, quoteSqlIdentifier, sqlLiteral } from "../src/export/sql-exporter.mjs";
import { generateRows } from "../src/generation/generation-engine.mjs";
import { buildGenerationPlan } from "../src/generation/generation-plan.mjs";
import { createI18n } from "../src/i18n/index.mjs";
import { exportErrorMessage } from "../src/i18n/workbench-messages.mjs";
import { DbxHostSchemaMetadataProvider } from "../src/providers/dbx-host-schema-metadata-provider.mjs";
import { DbxGenerationWorkbenchController } from "../src/workbench/dbx-generation-workbench-controller.mjs";

const TABLE = Object.freeze({ database: "app", schema: "public", table: "audit_log" });

function dataset(columns, rows, table = TABLE) {
  return {
    tableIdentity: "dbx:[\"connection-A\",\"app\",\"public\",\"audit_log\"]",
    table,
    columns,
    rows,
    generationContext: {
      seed: "test-seed",
      locale: "zh-CN",
      rowCount: rows.length,
      determinismProfile: "sha256-addressed-v1",
    },
  };
}

function assertExportError(action, code) {
  assert.throws(action, (error) => error instanceof ExportError && error.code === code);
}

function hostProvider(columns) {
  return new DbxHostSchemaMetadataProvider({
    capabilities: { schemaMetadataApi: true },
    async getTableMetadata() {
      return {
        columns,
        fieldCapabilities: { length: "supported", precision: "supported", scale: "supported", default: "supported" },
      };
    },
  });
}

function previewCore(calls = []) {
  return async (schema, options) => {
    calls.push({ schema, options: structuredClone(options) });
    const plan = buildGenerationPlan(schema, options);
    const generated = generateRows(plan);
    return JSON.parse(JSON.stringify({ plan, generated }));
  };
}

function controllerWith(columns, previewCalls = []) {
  return new DbxGenerationWorkbenchController({
    provider: hostProvider(columns),
    preview: previewCore(previewCalls),
    translator: createI18n("zh-CN"),
  });
}

describe("INSERT SQL export", () => {
  it("generates the documented header and one plain INSERT per preview row", () => {
    const content = exportInsertSql(dataset(["id", "task_id", "category", "file_name"], [
      { id: 471499, task_id: 657922, category: "br5kMa", file_name: "a" },
      { id: 831563, task_id: 841568, category: "KIUQDzIgiBLqc", file_name: "sNr45" },
    ]));

    assert.equal(content, `-- Generated by SchemaSeed
-- Synthetic test data only
-- Table: "public".audit_log
-- Rows: 2

INSERT INTO "public".audit_log (
    id,
    task_id,
    category,
    file_name
) VALUES (
    471499,
    657922,
    'br5kMa',
    'a'
);

INSERT INTO "public".audit_log (
    id,
    task_id,
    category,
    file_name
) VALUES (
    831563,
    841568,
    'KIUQDzIgiBLqc',
    'sNr45'
);
`);
    assert.equal(content.match(/INSERT INTO/g).length, 2, "one INSERT per row, never one multi-row VALUES list");
    assert.doesNotMatch(content, /\)\s*,\s*\(/, "no multi-row VALUES list");
    assert.doesNotMatch(content, /UPSERT|MERGE|ON CONFLICT|ON DUPLICATE|TRUNCATE|DELETE|DROP|CREATE TABLE/i);
    assert.equal(content.endsWith(");\n"), true);
  });

  it("serializes NULL, numbers, strings, booleans, dates, empty strings and Chinese text without type confusion", () => {
    const content = exportInsertSql(dataset(["n", "num", "ratio", "s", "empty", "flag", "day_value", "now", "zh"], [{
      n: null,
      num: 123,
      ratio: 123.45,
      s: "O'Reilly",
      empty: "",
      flag: true,
      day_value: "2025-03-04",
      now: "2025-03-04T12:34:56.123Z",
      zh: "安全合成数据🙂",
    }]), { header: false });

    assert.equal(content, `INSERT INTO "public".audit_log (
    n,
    num,
    ratio,
    s,
    empty,
    flag,
    day_value,
    now,
    zh
) VALUES (
    NULL,
    123,
    123.45,
    'O''Reilly',
    '',
    TRUE,
    '2025-03-04',
    '2025-03-04T12:34:56.123Z',
    '安全合成数据🙂'
);
`);
    assert.equal(content.includes("'NULL'"), false, "NULL must never become the string 'NULL'");
    assert.equal(content.includes("123,"), true, "numbers stay unquoted");
    assert.equal(content.includes("'123'"), false, "numbers must not be quoted");
    assert.equal(content.includes("''"), true, "the empty string stays an empty string literal");
  });

  it("keeps the literal serializer explicit for every supported scalar", () => {
    assert.equal(sqlLiteral(null), "NULL");
    assert.equal(sqlLiteral(123), "123");
    assert.equal(sqlLiteral(123.45), "123.45");
    assert.equal(sqlLiteral(-1), "-1");
    assert.equal(sqlLiteral("hello"), "'hello'");
    assert.equal(sqlLiteral("O'Reilly"), "'O''Reilly'");
    assert.equal(sqlLiteral(""), "''");
    assert.equal(sqlLiteral(true), "TRUE");
    assert.equal(sqlLiteral(false), "FALSE");
    assert.equal(sqlLiteral("中文"), "'中文'");
    assertExportError(() => sqlLiteral("\u0000"), "export_serialization_failed");
    assertExportError(() => sqlLiteral(Number.POSITIVE_INFINITY), "export_serialization_failed");
  });

  it("keeps the explicit dataset column order rather than the row object key order", () => {
    const content = exportInsertSql(dataset(["beta", "alpha"], [{ alpha: "row 1", beta: 1 }]), { header: false });
    assert.equal(content, `INSERT INTO "public".audit_log (
    beta,
    alpha
) VALUES (
    1,
    'row 1'
);
`);
  });

  it("quotes identifiers for the documented cross-dialect minimum", () => {
    assert.equal(quoteSqlIdentifier("id"), "id");
    assert.equal(quoteSqlIdentifier("audit_log"), "audit_log");
    assert.equal(quoteSqlIdentifier("order"), '"order"', "reserved words are quoted");
    assert.equal(quoteSqlIdentifier("select"), '"select"');
    assert.equal(quoteSqlIdentifier("public"), '"public"', "SQL-standard reserved words are quoted");
    assert.equal(quoteSqlIdentifier("CamelCase"), '"CamelCase"', "case-sensitive names keep their exact case");
    assert.equal(quoteSqlIdentifier("has space"), '"has space"');
    assert.equal(quoteSqlIdentifier("dash-name"), '"dash-name"');
    assert.equal(quoteSqlIdentifier('quo"te'), '"quo""te"');
    assert.equal(quoteSqlIdentifier("中文列"), '"中文列"');
  });

  it("qualifies the table with schema first, database second, and never database.schema.table together", () => {
    assert.equal(normalizeTableReference(TABLE).table, "audit_log");
    const schemaQualified = exportInsertSql(dataset(["id"], [{ id: 1 }]), { header: false });
    assert.match(schemaQualified, /INSERT INTO "public"\.audit_log \(/);

    const databaseQualified = exportInsertSql(dataset(["id"], [{ id: 1 }], { database: "app", table: "audit_log" }), { header: false });
    assert.match(databaseQualified, /INSERT INTO app\.audit_log \(/);
    assert.doesNotMatch(databaseQualified, /app\.public\./);

    const unqualified = exportInsertSql(dataset(["id"], [{ id: 1 }], { table: "audit_log" }), { header: false });
    assert.match(unqualified, /INSERT INTO audit_log \(/);

    const reserved = exportInsertSql(dataset(["id"], [{ id: 1 }], { schema: "my schema", table: "order" }), { header: false });
    assert.match(reserved, /INSERT INTO "my schema"\."order" \(/);
  });

  it("fails closed when the dataset has no table reference", () => {
    assertExportError(() => exportInsertSql(dataset(["id"], [{ id: 1 }], null)), "export_no_table_reference");
    assertExportError(() => normalizeTableReference({ schema: "public" }), "export_no_table_reference");
    assertExportError(() => normalizeTableReference({ database: 1, table: "t" }), "export_no_table_reference");
    assertExportError(() => exportInsertSql(dataset(["id"], [{ id: { nested: true } }])), "export_serialization_failed");
  });

  it("creates a .sql filename from the existing deterministic naming scheme", () => {
    assert.equal(createExportFilename("dbx:[\"c\",\"app\",\"public\",\"audit_log\"]", 20, "sql"), "schemaseed-dbx-c-app-public-audit_log-20rows.sql");
    assert.match(createExportFilename("table", 3, "sql"), /\.sql$/);
    assert.throws(() => createExportFilename("table", 3, "yaml"), TypeError);
  });
});

describe("INSERT SQL export reuses the current preview snapshot", () => {
  it("exports SQL, CSV and JSON from the same frozen dataset without regenerating", async () => {
    const previewCalls = [];
    const controller = controllerWith([{ name: "customer_id", dataType: "integer", nullable: false }], previewCalls);
    const view = await controller.setContext({ connectionId: "connection-A", database: "app", schema: "public", table: "customer" });
    assert.equal(view.status, "ready");

    const callsBeforeExport = previewCalls.length;
    const datasetBeforeExport = controller.currentDataset;
    const sql = controller.prepareExport("sql");
    const csv = controller.prepareExport("csv");
    const json = controller.prepareExport("json");

    assert.equal(previewCalls.length, callsBeforeExport, "export never calls Core generation");
    assert.equal(controller.currentDataset, datasetBeforeExport, "SQL keeps the current dataset snapshot");
    assert.equal(sql.filename, `schemaseed-dbx-connection-A-app-public-customer-${view.preview.rows.length}rows.sql`);
    assert.equal(sql.mimeType, "application/sql;charset=utf-8");
    assert.equal(sql.summary.format, "SQL");
    assert.equal(sql.summary.rowCount, view.preview.rows.length);
    assert.equal(controller.currentDataset.table.schema, "public");

    const jsonRows = JSON.parse(json.content);
    assert.deepEqual(jsonRows, view.preview.rows, "JSON shows the current preview rows");
    assert.ok(csv.content.startsWith("\uFEFFcustomer_id"));
    assert.match(sql.content, /INSERT INTO "public"\.customer \(/);
    for (const row of view.preview.rows) {
      assert.ok(sql.content.includes(sqlLiteral(row.customer_id)), `SQL contains preview customer_id ${row.customer_id}`);
    }

    const regenerated = await controller.dispatch({ type: "regenerate-same-seed" });
    assert.equal(controller.prepareExport("sql").content, sql.content, "same seed keeps the same SQL");
    assert.deepEqual(regenerated.preview.rows, view.preview.rows);

    await controller.dispatch({ type: "new-seed" });
    assert.notEqual(controller.prepareExport("sql").content, sql.content, "a new seed changes the SQL like CSV / JSON");
  });

  it("keeps SQL export available for a warning preview and blocked for a blocked plan", async () => {
    const warningController = controllerWith([
      { name: "customer_id", dataType: "integer", nullable: false },
      { name: "display_name", dataType: "varchar", nullable: false, length: 24 },
    ]);
    const warningView = await warningController.setContext({ connectionId: "connection-A", table: "customer" });
    assert.equal(warningView.status, "warning", "an inferred semantic candidate stays a non-blocking warning");
    assert.equal(warningView.export.enabled, true);
    assert.doesNotThrow(() => warningController.prepareExport("sql"));
    assert.match(warningController.prepareExport("sql").content, /INSERT INTO customer \(/);

    const blockedController = controllerWith([{ name: "customer_id", dataType: "integer", nullable: false }]);
    await blockedController.setContext({ connectionId: "connection-A", table: "customer" });
    const blocked = await blockedController.dispatch({
      type: "update-rule",
      column: "customer_id",
      rule: { kind: "random_integer", min: 0, max: Number.MAX_SAFE_INTEGER },
    });
    assert.equal(blocked.status, "blocked");
    assertExportError(() => blockedController.prepareExport("sql"), "export_blocked_plan");
  });

  it("captures the table reference through createExportDataset for the packaged runtime", async () => {
    const schema = {
      tableIdentity: "dbx:[\"c\",\"app\",\"public\",\"customer\"]",
      columns: [{ name: "customer_id", dataType: "integer", nullable: false }],
    };
    const plan = buildGenerationPlan(schema, { seed: "snapshot", rowCount: 2 });
    const generated = generateRows(plan);
    const captured = createExportDataset(plan, generated, { table: { connectionId: "c", database: "app", schema: "public", table: "customer" } });

    assert.deepEqual(captured.table, { database: "app", schema: "public", table: "customer" });
    assert.equal(Object.isFrozen(captured.table), true);
    assert.match(exportInsertSql(captured), /INSERT INTO "public"\.customer \(/);
    assert.throws(
      () => createExportDataset(plan, generated, { table: { database: 42, table: "customer" } }),
      (error) => error instanceof ExportError && error.code === "export_no_table_reference",
    );
  });
});

describe("INSERT SQL export i18n coverage", () => {
  it("localizes the button and the SQL-specific export failures in both locales", () => {
    const zh = createI18n("zh-CN");
    const en = createI18n("en-US");
    assert.equal(zh("export.sql"), "导出 INSERT SQL");
    assert.equal(en("export.sql"), "Export INSERT SQL");
    assert.notEqual(zh("export.sql"), en("export.sql"));

    for (const locale of [zh, en]) {
      for (const key of ["export.sql", "export.error.export_no_table_reference", "export.error.export_serialization_failed"]) {
        assert.equal(locale.has(key), true, `${locale.locale} localizes ${key}`);
      }
    }
    const localized = exportErrorMessage(Object.assign(new ExportError("export_no_table_reference", "raw"), {}), zh);
    assert.match(localized, /export_no_table_reference/);
    assert.match(localized, /database \/ schema \/ table/);
    assert.doesNotMatch(localized, /export\.error\.export_error/, "a known SQL export code has dedicated copy");
    const unknown = exportErrorMessage({ code: "export_unknown_future_code" }, en);
    assert.match(unknown, /Export failed/, "unknown codes fall back to the generic localized copy");
  });
});
